// <auto-generated />
using Lab15.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab15.Migrations
{
    [DbContext(typeof(UsersContext))]
    [Migration("20250228224021_AddFullNameCol")]
    partial class AddFullNameCol
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab15.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("UserID");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Lab15.Entities.FrontendUser", b =>
                {
                    b.HasBaseType("Lab15.Entities.User");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("FrontendUser");
                });

            modelBuilder.Entity("Lab15.Entities.KitchenUser", b =>
                {
                    b.HasBaseType("Lab15.Entities.User");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("KitchenUser");
                });
#pragma warning restore 612, 618
        }
    }
}
