// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;

namespace Lab15.Entities;

public partial class Reservation
{
    [Column("id")]
    public int Id { get; set; }


    [Column("first_name")]
    public string FirstName { get; set; }

    [Column("last_name")]
    public string LastName { get; set; }

    [NotMapped]
    //[IgnoreDataMember]
    public string FullName => $"{FirstName} {LastName}";


    [Column("birth_day")]
    public string BirthDay { get; set; }

    [NotMapped]
    public string Day => BirthDay.Split("-")[1];

    [NotMapped]
    public string Month => BirthDay.Split("-")[0];

    [NotMapped]
    public string Year => BirthDay.Split("-")[2];


    [Column("gender")]
    public string Gender { get; set; }

    [Column("phone_number")]
    public string PhoneNumber { get; set; }

    [Column("email_address")]
    public string EmailAddress { get; set; }

    [Column("number_guest")]
    public int NumberGuest { get; set; }

    [Column("street_address")]
    public string StreetAddress { get; set; }

    [Column("apt_suite")]
    public string AptSuite { get; set; }

    [Column("city")]
    public string City { get; set; }

    [Column("state")]
    public string State { get; set; }

    [Column("zip_code")]
    public string ZipCode { get; set; }

    [Column("room_type")]
    public string RoomType { get; set; }

    [Column("room_floor")]
    public string RoomFloor { get; set; }

    [Column("room_number")]
    public string RoomNumber { get; set; }

    [Column("total_bill")]
    public double TotalBill { get; set; }

    [Column("payment_type")]
    public string PaymentType { get; set; }

    [Column("card_type")]
    public string CardType { get; set; }

    [Column("card_number")]
    public string CardNumber { get; set; }


    [Column("card_exp")]
    public string CardExp { get; set; }


    [NotMapped]
    public string CardExpMonth
    {
        get => !string.IsNullOrEmpty(CardExp) && CardExp.Contains("/") ? CardExp.Split('/')[0] : "";
        set
        {
            if (!string.IsNullOrEmpty(value) && !string.IsNullOrEmpty(CardExp) && CardExp.Contains("/"))
                CardExp = value + "/" + CardExp.Split('/')[1];
        }
    }
    

    [NotMapped]
    public string CardExpYear
    {
        get => !string.IsNullOrEmpty(CardExp) && CardExp.Contains("/") ? CardExp.Split('/')[1] : "";
        set
        {
            if (!string.IsNullOrEmpty(value) && !string.IsNullOrEmpty(CardExp) && CardExp.Contains("/"))
                CardExp = CardExp.Split('/')[0] + "/" + value;
        }
    }


    [Column("card_cvc")]
    public string CardCvc { get; set; }

    [Column("arrival_time")]
    public DateTime ArrivalTime { get; set; }

    [Column("leaving_time")]
    public DateTime LeavingTime { get; set; }

    [Column("check_in")]
    public bool CheckIn { get; set; }

    [Column("break_fast")]
    public int BreakFast { get; set; }

    [Column("lunch")]
    public int Lunch { get; set; }

    [Column("dinner")]
    public int Dinner { get; set; }

    [Column("cleaning")]
    public bool Cleaning { get; set; }

    [Column("towel")]
    public bool Towel { get; set; }

    [Column("s_surprise")]
    public bool SSurprise { get; set; }

    [Column("supply_status")]
    public bool SupplyStatus { get; set; }

    [Column("food_bill")]
    public int FoodBill { get; set; }

}
